"""empty message

Revision ID: 0c29c3ba40e0
Revises: 
Create Date: 2024-01-06 12:28:02.105991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c29c3ba40e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['book_id'])
        batch_op.drop_constraint('book_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('book_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'booktable', ['ISBN'], ['ISBN'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'manager', ['manager_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('booktable', schema=None) as batch_op:
        batch_op.drop_constraint('booktable_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'manager', ['manager_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('lend', schema=None) as batch_op:
        batch_op.drop_constraint('lend_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('lend_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'reader', ['reader_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'book', ['book_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('reserve', schema=None) as batch_op:
        batch_op.drop_constraint('reserve_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('reserve_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('reserve_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'booktable', ['booktable_ISBN'], ['ISBN'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'reader', ['reader_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'book', ['book_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserve', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reserve_ibfk_3', 'book', ['book_id'], ['id'])
        batch_op.create_foreign_key('reserve_ibfk_2', 'reader', ['reader_id'], ['id'])
        batch_op.create_foreign_key('reserve_ibfk_1', 'booktable', ['booktable_ISBN'], ['ISBN'])

    with op.batch_alter_table('lend', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('lend_ibfk_1', 'book', ['book_id'], ['id'])
        batch_op.create_foreign_key('lend_ibfk_2', 'reader', ['reader_id'], ['id'])

    with op.batch_alter_table('booktable', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('booktable_ibfk_1', 'manager', ['manager_id'], ['id'])

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('book_ibfk_1', 'booktable', ['ISBN'], ['ISBN'])
        batch_op.create_foreign_key('book_ibfk_2', 'manager', ['manager_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
