"""empty message

Revision ID: 40ff40d3876a
Revises: 290e7a6a6fb4
Create Date: 2023-12-30 11:48:45.091433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40ff40d3876a'
down_revision = '290e7a6a6fb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manager', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=45), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manager', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
