"""empty message

Revision ID: 50073b8e6450
Revises: 9ef91be0df64
Create Date: 2023-12-30 12:09:53.959506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50073b8e6450'
down_revision = '9ef91be0df64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id', 'email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('captcha')
    # ### end Alembic commands ###
