"""empty message

Revision ID: 73a781f5d686
Revises: 
Create Date: 2024-01-02 11:12:36.105577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a781f5d686'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id', 'email')
    )
    op.create_table('manager',
    sa.Column('work_num', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('work_num')
    )
    op.create_table('reader',
    sa.Column('reader_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('fine', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('borrow_num', sa.Integer(), nullable=False, comment='一名读者最多只能借阅十本图书，且每本图书最多只能借两个月'),
    sa.PrimaryKeyConstraint('reader_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reader')
    op.drop_table('manager')
    op.drop_table('captcha')
    # ### end Alembic commands ###
