"""empty message

Revision ID: 76bed6449870
Revises: 
Create Date: 2024-01-03 17:27:32.484785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76bed6449870'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('reader',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('sex', sa.String(length=1), nullable=False),
    sa.Column('fine', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('borrow_num', sa.Integer(), nullable=False, comment='一名读者最多只能借阅十本图书，且每本图书最多只能借两个月'),
    sa.CheckConstraint('borrow_num >= 0 AND borrow_num <= 10', name='check_borrow_num'),
    sa.CheckConstraint('fine >= 0', name='check_fine'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reader')
    op.drop_table('manager')
    # ### end Alembic commands ###
