"""empty message

Revision ID: 9ef91be0df64
Revises: 207f0a33d911
Create Date: 2023-12-30 12:01:25.936110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ef91be0df64'
down_revision = '207f0a33d911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('email_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=6), nullable=False),
    sa.PrimaryKeyConstraint('email_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
